CustomerPortal/Controllers/InvoiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CustomerPortalModels;
using CustomerPortal.Models;
using NCommon.Specifications;
using SAPModels;

namespace CustomerPortal.Controllers
{
    [Authorize]
    public class InvoiceController : _ApplicationController
    {
        private readonly IInvoiceRepository _invoiceRepo;
        private readonly IUserActivityRepository _userActivityRepo;

        public InvoiceController(IInvoiceRepository invoiceRepo, IUserActivityRepository userActivityRepo)
        {
            _invoiceRepo = invoiceRepo;
            _userActivityRepo = userActivityRepo;
        }

        public ActionResult Index()
        {
            var invoices = _invoiceRepo.GetAll(GetUser().CustomerNumber).Where(x => x.InvoiceDate > DateTime.Now.AddDays(-30)).Take(100).ToList();
            //var invoices = _invoiceRepo.GetAll(new Specification<Invoice>(x => x.CustomerNumber == GetUser().CustomerNumber));
            return View(invoices);
        }

        [HttpPost]
        public ActionResult Index(string searchData)
        {
            searchData = searchData.ToLower();

            _userActivityRepo.Add(new UserActivity()
            {
                User = User.Identity.Name,
                Action = "Invoice Search",
                Message = "Searched for invoice: " + searchData
            });
            
            var invoices = _invoiceRepo.GetAll(new Specification<Invoice>(x => x.CustomerNumber == GetUser().CustomerNumber && (x.PONumber.ToLower().Contains(searchData) || x.InvoiceNumber.ToString().Contains(searchData))));
            return View(invoices);
        }

        [HttpPost]
        public ActionResult AdvancedSearch(InvoiceAdvancedSearchModel model)
        {
            var invoices = _invoiceRepo.GetAll(GetUser().CustomerNumber);

            if (!string.IsNullOrEmpty(model.StartDate))
                invoices = invoices.Where(x => x.InvoiceDate >= DateTime.Parse(model.StartDate));

            if (!string.IsNullOrEmpty(model.EndDate))
                invoices = invoices.Where(x => x.InvoiceDate <= DateTime.Parse(model.EndDate));

            if (!string.IsNullOrEmpty(model.InvoiceNumber))
                invoices = invoices.Where(x => x.InvoiceNumber.ToString().Contains(model.InvoiceNumber.ToLower()));

            if (!string.IsNullOrEmpty(model.PONumber))
                invoices = invoices.Where(x => x.PONumber.ToLower().Contains(model.PONumber.ToLower()));

            if (!string.IsNullOrEmpty(model.Status))
                invoices = invoices.Where(x => x.Status.ToLower().Contains(model.Status.ToLower()));

            if (model.AmountLow != 0.0)
                invoices = invoices.Where(x => x.InvoiceAmount >= model.AmountLow);

            if (model.AmountHigh != 0.0)
                invoices = invoices.Where(x => x.InvoiceAmount <= model.AmountHigh);

            var invoiceList = invoices.OrderByDescending(x => x.InvoiceDateSAP).Take(100).ToList();

            if (invoiceList.Count == 0)
            {
                ViewData["emptyMessage"] = "Sorry! No results match your search terms.";
            }

            return View("Index", invoiceList);
        }

        public ActionResult PrintInvoice(int invoiceNumber)
        {
            _userActivityRepo.Add(new UserActivity()
            {
                User = User.Identity.Name,
                Action = "Invoice Print",
                Message = "Printed invoice: " + invoiceNumber
            });

            string pdf = new InvoiceService().PrintInvoice(invoiceNumber.ToString());
            return File(@"\\fred\reprint\" + pdf, "application/pdf");
        }

        public ActionResult InvoiceTile()
        {
            try
            {
                var invoices = _invoiceRepo.GetAll(GetUser().CustomerNumber).Where(x => x.InvoiceDate > DateTime.Now.AddDays(-30)).Take(5).ToList();
                return PartialView(invoices);
            }
            catch (Exception)
            {
                return PartialView();
            }
        }
    }
}

CustomerPortal/Views/Invoice/Index.cshtml
@model IEnumerable<SAPModels.Invoice>
@using MvcContrib.UI.Grid
@{
    ViewBag.Title = "Invoices";
}
@section Scripts
{
    <link href="@Url.Content("~/Scripts/__jquery.tablesorter/themes/custom/style.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Scripts/__jquery.tablesorter/addons/pager/jquery.tablesorter.pager.css")" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="../../Scripts/__jquery.tablesorter/jquery.tablesorter.js?1"></script>
    <script type="text/javascript" src="../../Scripts/__jquery.tablesorter/addons/pager/jquery.tablesorter.pager.js?1"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $("#invoiceList")
            .tablesorter({ widthFixed: true })
            .tablesorterPager({ container: $("#pager"), positionFixed: false });
        });
    </script>
}

<h2 style="float:left">Invoices</h2>

@{
    Html.RenderPartial("InvoiceSearch", new CustomerPortal.Models.InvoiceAdvancedSearchModel());
    Html.RenderPartial("InvoiceList", Model);
}

CustomerPortal/Views/Invoice/InvoiceList.cshtml
@model IEnumerable<SAPModels.Invoice>
@using MvcContrib.UI.Grid
@{
    var colors = new List<string>() { "yellow", "light-blue", "red", "green" };
    
    if (Model != null && Model.Count() > 0)
    {
        Html.Grid(Model)
            .Attributes(@id => "invoiceList", @class => "tablesorter", style => "width:100%")
            .RowAttributes(row => new MvcContrib.Hash(data => @Html.Raw(Json.Encode(row.Item)), @class => "clickableRow " + colors[Model.ToList().IndexOf(row.Item) % 4]))
            .Columns(
                col =>
                {
                    col.For(x => Html.ActionLink(x.InvoiceNumber.ToString(), "PrintInvoice", new { invoiceNumber = x.InvoiceNumber }, new { target = "_blank" })).Named("Invoice Number");
                    col.For(x => x.PONumber);
                    col.For(x => x.Status);
                    col.For(x => x.InvoiceDate.ToShortDateString()).Named("Invoice Date");
                    col.For(x => x.InvoiceAmount).Format("{0:c}").Attributes(@class => "right-column");
                }).Render();
    }
    else
    {
        <br class="clear" />
        <h4 class="emptyMessage">Sorry! No results match your search terms.
            <br />
            Please try again.
            <br class="clear"/>
            <br class="clear"/>
            If you are still having trouble, try the <a href="#" onclick="toggleAdvancedSearch()">Advanced Search</a> option to refine your search.
        </h4>
    }
    if (Model != null && Model.Count() > 10)
    {
        Html.RenderPartial("PagerControl");
    }
}

<script type="text/javascript">
    $(function () {
        $(".clickableRow").click(function () {
            var data = JSON.parse($(this).attr("data"));
            window.location.href = '/Invoice/PrintInvoice?invoiceNumber=' + data.InvoiceNumber;
        });
    });
</script>

CustomerPortal/Views/Invoice/InvoiceSearch.cshtml
@model CustomerPortal.Models.InvoiceAdvancedSearchModel

@using (Html.BeginForm("Index", "Invoice", FormMethod.Post, new { id = "basicSearch", @class = "searchInvoices search" }))
{
    Html.RenderPartial("Search");
}

@using (Html.BeginForm("AdvancedSearch", "Invoice", FormMethod.Post, new { @class = "searchProducts search" }))
{
    <fieldset id="advancedSearch">
    <legend>Advanced Search</legend>
        <br />
        <div class="input-control text full-size" data-role="input">
            @Html.LabelFor(x => x.InvoiceNumber)
            @Html.TextBoxFor(x => x.InvoiceNumber)
        </div>
        <br />
        <br />
        <div class="input-control text full-size" data-role="input">
            @Html.LabelFor(x => x.PONumber)
            @Html.TextBoxFor(x => x.PONumber)
        </div>
        <br />
        <br />
        <div class="input-control full-size select">    
            @Html.LabelFor(x => x.Status)
            <select name="Status" autocomplete=off>
                <option selected="selected" value="">Any</option>
                <option>Open</option>
                <option>Paid</option>
            </select>
        </div>
        <br />
        <br />
        <div class="input-control text" data-role="input">
            @Html.Label("Date")
            <div class="input-control text full-size" data-role="datepicker" data-format="mm/dd/yyyy" data-date="1972-12-21">
                <input type="text" id="StartDate" name="StartDate" placeholder="Start Date" />
                <button class="button"><span class="fa fa-calendar"></span></button>
            </div>
            <div class="input-control text full-size" data-role="datepicker" data-format="mm/dd/yyyy" data-date="1972-12-21">
                <input type="text" name="EndDate" placeholder="End Date" />
                <button class="button"><span class="fa fa-calendar"></span></button>
            </div>
        </div>
        <br />
        <br />
        <br />
        <br />
        <br />
        <div class="input-control text full-size" data-role="input">
            @Html.Label("Amount")
            <span class="fa fa-dollar prepend-icon"></span>
            <input type="text" name="AmountLow" placeholder="Minimum Amount"/>
        </div>
        <div class="input-control text full-size" data-role="input">
            <span class="fa fa-dollar prepend-icon"></span>
            <input type="text" name="AmountHigh" placeholder="Maximum Amount" />
        </div>
        <br />
                <button type="submit" class="button primary" style="float:right">Search</button>
                <button type="button" class="button bg-red fg-white" style="float:left" onclick="toggleAdvancedSearch()">Back</button>
    </fieldset>
}

<script type="text/javascript">
    $(function () {
        var today = new Date()
        var priorDate = new Date().setDate(today.getDate() - 30)
        priorDate = new Date(priorDate);
        var dd = priorDate.getDate();
        var mm = priorDate.getMonth() + 1; //January is 0!
        var yyyy = priorDate.getFullYear();

        if (dd < 10) {
            dd = '0' + dd
        }

        if (mm < 10) {
            mm = '0' + mm
        }

        $('#StartDate').val(mm + '/' + dd + '/' + yyyy);
    });
</script>

CustomerPortal/Views/Invoice/InvoiceTile.cshtml
@model IEnumerable<SAPModels.Invoice>
@using MvcContrib.UI.Grid
@{
    var colors = new List<string>() { "yellow", "light-blue", "red", "green" };
        
    if (Model != null && Model.Count() > 0)
    {
        Html.Grid(Model)
            .Attributes(@id => "invoiceList", @class => "tablesorter tile-table", style => "width:100%")
            .RowAttributes(row => new MvcContrib.Hash(@class => colors[Model.ToList().IndexOf(row.Item) % 4]))
            .Columns(
                col =>
                {
                    col.For(x => Html.ActionLink(x.InvoiceNumber, "PrintInvoice", new { invoiceNumber = x.InvoiceNumber }, new { target = "_blank" })).Named("Invoice Number");
                    col.For(x => x.PONumber);
                    col.For(x => x.Status);
                    col.For(x => x.InvoiceDate.ToShortDateString()).Named("Invoice Date");
                    col.For(x => x.InvoiceAmount).Format("{0:c}");
                }).Render();
    }
}