CustomerPortal/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CustomerPortalModels;
using CustomerPortal.Filters;
using System.Data;
using System.Data.SqlClient;
using CustomerPortal.Models;
using NCommon.Specifications;
using SAPModels;

namespace CustomerPortal.Controllers
{
    [Authorize]
    [CustomerNumberRequired]
    public class OrderController : _ApplicationController
    {
        private readonly IOrderRepository _orderRepo;
        private readonly IOrderLineRepository _orderLineRepo;
        private readonly IUserActivityRepository _userActivityRepo;

        public OrderController(IOrderRepository orderRepo, IOrderLineRepository orderLineRepo, IUserActivityRepository userActivityRepo)
        {
            _orderRepo = orderRepo;
            _orderLineRepo = orderLineRepo;
            _userActivityRepo = userActivityRepo;
        }

        public ActionResult Index()
        {
            //var orders = _orderRepo.GetAll(GetUser().CustomerNumber).Take(100).ToList();
            var orders = _orderRepo.GetAll(new Specification<Order>(x => 
                x.SoldTo == GetUser().CustomerNumber));
            return View(orders);
        }

        [HttpPost]
        public ActionResult Index(string searchData)
        {
            searchData = searchData.ToLower();

            _userActivityRepo.Add(new UserActivity()
            {
                User = User.Identity.Name,
                Action = "Order Search",
                Message = "Searched for order: " + searchData
            });
            var orders = _orderRepo.GetAll(new Specification<Order>(x => 
                x.SoldTo == GetUser().CustomerNumber &&
                (x.SalesOrder.ToLower().Contains(searchData) || x.PurchaseOrder.ToLower().Contains(searchData))));
            return View(orders);
        }

        [HttpPost]
        public ActionResult AdvancedSearch(OrderAdvancedSearchModel model)
        {
            var orders = _orderRepo.GetAll(GetUser().CustomerNumber);

            var spec = new Specification<Order>(x =>
                !string.IsNullOrEmpty(model.StartDate) ? x.OrderDate >= DateTime.Parse(model.StartDate) : false &&
                !string.IsNullOrEmpty(model.EndDate) ? x.OrderDate <= DateTime.Parse(model.EndDate) : false &&
                !string.IsNullOrEmpty(model.OrderNumber) ? x.SalesOrder.ToLower().Contains(model.OrderNumber.ToLower()) : false
            );

            if (!string.IsNullOrEmpty(model.StartDate))
                orders = orders.Where(x => x.OrderDate >= DateTime.Parse(model.StartDate));

            if (!string.IsNullOrEmpty(model.EndDate))
                orders = orders.Where(x => x.OrderDate <= DateTime.Parse(model.EndDate));

            if (!string.IsNullOrEmpty(model.OrderNumber))
                orders = orders.Where(x => x.SalesOrder.ToLower().Contains(model.OrderNumber.ToLower()));

            if (!string.IsNullOrEmpty(model.PONumber))
                orders = orders.Where(x => x.PurchaseOrder.Contains(model.PONumber.ToLower()));

            if (!string.IsNullOrEmpty(model.Status))
                orders = orders.Where(x => x.Status.ToLower().Contains(model.Status.ToLower()));

            if (model.ValueLow != 0.0)
                orders = orders.Where(x => x.OrderValue >= model.ValueLow);

            if (model.ValueHigh != 0.0)
                orders = orders.Where(x => x.OrderValue <= model.ValueHigh);

            var orderList = orders.OrderByDescending(x => x.OrderDateSAP).Take(100).ToList();

            if (orderList.Count == 0)
            {
                ViewData["emptyMessage"] = "Sorry! No results match your search terms.";
            }

            return View("Index", orderList);
        }

        public ActionResult RecentOrderTile()
        {
            try
            {
                var orders = _orderRepo.GetAll(GetUser().CustomerNumber).Take(5).ToList();
                return PartialView(orders);
            }
            catch (Exception)
            {
                return PartialView();
            }
        }

        public ActionResult OrderDetail(string orderNumber)
        {
            var order = _orderRepo.Get(orderNumber, GetUser().CustomerNumber);
            order.LineItems = _orderLineRepo.Get(orderNumber).ToList();

            var sql = @"SELECT       PRD.prd.VBFA.VBELN, PRD.prd.LIKP.VBELN AS Delivery, PRD.prd.LIKP.ERDAT, PRD.prd.LIKP.BOLNR, PRD.prd.LIKP.ROUTE, PRD.prd.VTTK.TDLNR, PRD.prd.LFA1.NAME1, PRD.prd.TVROT.BEZEI
                      FROM         PRD.prd.VBFA INNER JOIN
                                   PRD.prd.LIKP ON PRD.prd.VBFA.MANDT = PRD.prd.LIKP.MANDT AND PRD.prd.VBFA.VBELN = PRD.prd.LIKP.VBELN INNER JOIN
                                   PRD.prd.VTTK ON PRD.prd.VBFA.MANDT = PRD.prd.VTTK.MANDT INNER JOIN
                                   PRD.prd.VTTP ON PRD.prd.VBFA.MANDT = PRD.prd.VTTP.MANDT AND PRD.prd.VBFA.VBELN = PRD.prd.VTTP.VBELN AND PRD.prd.VTTK.TKNUM = PRD.prd.VTTP.TKNUM INNER JOIN
                                   PRD.prd.LFA1 ON PRD.prd.VBFA.MANDT = PRD.prd.LFA1.MANDT AND PRD.prd.VTTK.TDLNR = PRD.prd.LFA1.LIFNR LEFT OUTER JOIN
                                   PRD.prd.TVROT ON PRD.prd.LIKP.MANDT = PRD.prd.TVROT.MANDT AND PRD.prd.LIKP.ROUTE = PRD.prd.TVROT.ROUTE
                      WHERE       (PRD.prd.VBFA.MANDT = '100') AND (PRD.prd.VBFA.VBELV = '" + orderNumber + "') AND (PRD.prd.VBFA.VBTYP_N = 'J') " +
                      "GROUP BY     PRD.prd.VBFA.VBELN, PRD.prd.LIKP.VBELN, PRD.prd.LIKP.ERDAT, PRD.prd.LIKP.BOLNR, PRD.prd.LIKP.ROUTE, PRD.prd.VTTK.TDLNR, PRD.prd.LFA1.NAME1, PRD.prd.TVROT.BEZEI";

            SqlConnection conn = new SqlConnection("Data Source=Jed;Initial Catalog=PRD;User ID=spongebob;Password=benjamin");
            DataSet dataSet = new DataSet();
            SqlDataAdapter adapter = new SqlDataAdapter(sql, conn);
            if (conn.State == ConnectionState.Closed)
                conn.Open();
            adapter.Fill(dataSet);
            conn.Close();

            order.PackingSlips = new List<SAPModels.PackingSlip>();
            if (dataSet.Tables.Count > 0)
            {
                DataTable table = dataSet.Tables[0];
                for (int i = 0; i < table.Rows.Count; i++)
                {
                    order.PackingSlips.Add(new SAPModels.PackingSlip()
                    {
                        Carrier = table.Rows[i]["NAME1"].ToString(),
                        TrackingNumber = table.Rows[i]["BOLNR"].ToString(),
                        TrackingLink = TrackingFactory.GetLink(table.Rows[i]["BOLNR"].ToString(), table.Rows[i]["TDLNR"].ToString()),
                        DeliveryDate = table.Rows[i]["ERDAT"].ToString(),
                        DeliveryNumber = table.Rows[i]["VBELN"].ToString(),
                    });
                }
            }

            _userActivityRepo.Add(new UserActivity()
            {
                User = User.Identity.Name,
                Action = "View Order",
                Message = "Viewed order: " + orderNumber
            });
            return View(order);
        }

        public ActionResult PrintPackingSlip(string dlvNumber)
        {
            _userActivityRepo.Add(new UserActivity()
            {
                User = User.Identity.Name,
                Action = "Packing Slip Print",
                Message = "Printed packing slip: " + dlvNumber
            });

            string pdf = new OrderService().PrintPackingSlip(dlvNumber);
            return File(@"\\fred\reprint\" + pdf, "application/pdf", pdf);
        }
    }
}

CustomerPortal/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CustomerPortalModels;
using System.Web.Security;
using CustomerPortal.Models;

namespace CustomerPortal.Controllers
{
    [Authorize]
    public class UserController : _ApplicationController
    {
        public UserController()
        {
        }

        public ActionResult Index()
        {
            var users = userRepo.GetAll().Take(100).ToList();
            return View(users);
        }

        [HttpPost]
        public ActionResult Index(string searchData)
        {
            searchData = searchData.ToLower();
            var users = userRepo.GetAll().Where(x => x.UserName.ToLower().Contains(searchData) || x.DisplayName.ToLower().Contains(searchData)).Take(100).ToList();
            return View(users);
        }

        [HttpPost]
        public ActionResult AdvancedSearch(UserAdvancedSearchModel model)
        {
            var userQuery = userRepo.GetAll();

            if (!string.IsNullOrEmpty(model.UserName))
                userQuery = userQuery.Where(x => x.UserName.ToLower().Contains(model.UserName.ToLower()));

            if (!string.IsNullOrEmpty(model.DisplayName))
                userQuery = userQuery.Where(x => x.DisplayName.ToLower().Contains(model.DisplayName.ToLower()));

            var users = userQuery.ToList();

            if (!string.IsNullOrEmpty(model.AccountType))
                users = users.Where(x => x.AccountType.ToLower().Contains(model.AccountType.ToLower())).ToList();

            if (model.AccountType == "Customer" && !string.IsNullOrEmpty(model.CustomerNumber))
                users = users.Where(x => x.CustomerNumber.ToLower() == model.CustomerNumber.ToLower()).ToList();

            if (users.Count() == 0)
            {
                ViewData["emptyMessage"] = "Sorry! No results match your search terms.";
            }

            return View("Index", users);
        }
    }
}

CustomerPortal/Views/Shared/AddToCartPartial.cshtml
@model CustomerPortal.Models.AddToCartModel

@using (Html.BeginForm("AddToCart", "ShoppingCart", FormMethod.Post, new { @class = "addToCart" }))
{
    <div class="input-control input-control-small text" style="width: 10px">
        @Html.HiddenFor(x => x.SKU)
        @Html.TextBoxFor(x => x.Quantity, new { type = "number", min = "1" })
        <button class="button">
            <span class="fa fa-cart-plus"></span>
        </button>
    </div>
}

CustomerPortal/Views/Shared/ImpersonateTile.cshtml
@model CustomerPortal.Models.ImpersonateUserModel

@using (Html.BeginForm("ImpersonateTile", "Account"))
{
    var user = ((CustomerPortalModels.User)Session["user"]);
        if (user.CustomerNumber != null)
        {
            <text>Currently Impersonating @user.CustomerNumber</text>
    }

    if (ViewData["custs"] == null)
    {
        <div class="input-control text" style="width: 286px">
            <input type="text" name="CustomerNumber" placeholder="Enter Customer Number..." />
            <button class="button">
                <span class="fa fa-lg fa-user-secret"></span>
            </button>
        </div>
    }
    else
    {
        <div class="input-control text" style="width: 286px">
            <select id="CustomerNumber" name="CustomerNumber">
                @foreach (var opt in ((List<SAPModels.Customer>)ViewData["custs"]).OrderBy(x => x.Name))
                {
                    int index = opt.Number.IndexOf(".");
                    if (index > 0)
                    {
                        <option value=@opt.Number.Substring(0, index) @(opt.ParentNumber == user.CustomerNumber ? "selected=selected" : "")>@opt.Name</option>
                    }
                    else{
                        <option value=@opt.Number @(opt.ParentNumber == user.CustomerNumber ? "selected=selected" : "")>@opt.Name</option>
                    }
                }
            </select>
            <button class="button">
                <span class="fa fa-lg fa-user-secret"></span>
            </button>
        </div>
    }
}

CustomerPortal/Views/Shared/PagerControl.cshtml
<div id="pager" class="pager">
    <form>
    <img class="first" src="/Images/first.png">
    <img class="prev" src="/Images/prev.png">
    <input class="pagedisplay" type="text">
    <img class="next" src="/Images/next.png">
    <img class="last" src="/Images/last.png">
    <select class="pagesize">
        <option value="10" selected="selected">10</option>
        <option value="25">25</option>
        <option value="50">50</option>
        <option value="100">100</option>
    </select>
    </form>
</div>

CustomerPortal/Views/Shared/ProductPhotoLink.cshtml
@model CustomerPortalModels.Product

<a href="~/Product/ViewProduct?sku=@Model.SKU">
<image src='http://www.westchestergear.com/wp-content/uploads/ProductImages/@(Model.BasePartNumber.Replace("/", "~") + ".png")' height='50' width='50' />
@Model.SKU
</a>


CustomerPortal/Views/Shared/Search.cshtml

    <div class="input-control text margin20" style="width: 300px">
        <input type="text" name="searchData" placeholder="Search..." />
        <button class="button">
            <span class="fa fa-search"></span>
        </button>
        <a href="#" onclick="toggleAdvancedSearch()" class="advancedSearchLink">Advanced Search</a>
    </div>

<script type="text/javascript">
    function toggleAdvancedSearch() {
        $("#advancedSearch").toggle();
    }
</script>

CustomerPortal/Views/Shared/ShipToControl.cshtml
@model IEnumerable<SAPModels.ShipTo>

<div id="shipTos">
    <h4 style="float:left">Your Address Book</h4>
    <div class="advancedSearchLink">
        <a href="#" onclick="toggleAdvancedSearch()">
        <span class="fa fa-search"></span> Search Addresses</a>
    </div>

    @{
        Html.RenderPartial("ShipToSearch");
        
        <br />
        <br />
        <br />
        <div id="shipToContainer">
            @{Html.RenderAction("ShipToList", "ShipTo");}
        </div>
    }
</div>

<script type="text/javascript">
    function toggleAdvancedSearch() {
        $("#advancedSearch").toggle();
    }
    $(function () {
        $("#shipToList")
                    .tablesorter({
                        widthFixed: true,
                        headers: { 0: { sorter: false} },
                        sortList: [[4, 0], [2, 0], [1, 0]]
                     })
                    .tablesorterPager({ container: $("#pager"), positionFixed: false, size: 5 });
        $("clickableRow").click(function () {
            alert("test");
        });
    });
</script>

CustomerPortal/Views/Shared/_FooterPartial.cshtml
<div class="bottom-menu-wrapper">
    <ul class="horizontal-menu compact">
        <li><a>&copy; @DateTime.Now.Year West Chester Protective Gear</a></li>
        <li class="place-right">
            <div class="main-content clear-float">
                <div class="tile-area no-padding">
                    <div class="tile-group no-margin no-padding">
@*                        <a href="/Help/" class="fg-white">
                            <div class="tile-small bg-orange fg-white" data-role="tile">
                                <div class="tile-content iconic">
                                    <span class="icon fa fa-question"></span>
                                </div>
                            </div>
                        </a>  *@
                        <a href="/Bug/" class="fg-white">
                            <div class="tile-small bg-yellow fg-white" data-role="tile">
                                <div class="tile-content iconic">
                                    <span class="icon fa fa-bug"></span>
                                </div>
                            </div>
                        </a>  
                        <a href="https://www.facebook.com/pages/West-Chester-Protective-Gear/235840629898043?fref=ts" class="fg-white">
                            <div class="tile-small bg-blue fg-white" data-role="tile">
                                <div class="tile-content iconic">
                                        <span class="icon fa fa-facebook"></span>
                                </div>
                            </div>
                        </a>  
                        <a href="https://twitter.com/WestChesterGear" class="fg-white">
                            <div class="tile-small bg-green fg-white" data-role="tile">
                                <div class="tile-content iconic">
                                        <span class="icon fa fa-twitter"></span>
                                </div>
                            </div>
                        </a>  
                        <a href="https://www.linkedin.com/company/630513?trk=tyah&trkInfo=clickedVertical%3Acompany%2Cidx%3A1-1-1%2CtarId%3A1434313818926%2Ctas%3Awest%20chester%20pro" class="fg-white">
                            <div class="tile-small bg-lightBlue fg-white" data-role="tile">
                                <div class="tile-content iconic"><span class="icon fa fa-linkedin"></span>
                                </div>
                            </div>
                        </a>  
                        <a href="https://www.youtube.com/user/WCProtectiveGear" class="fg-white">
                            <div class="tile-small bg-red fg-white" data-role="tile">
                                <div class="tile-content iconic">
                                        <span class="icon fa fa-youtube"></span>
                                </div>
                            </div>
                        </a>  
                    </div>
                </div>
            </div>
        </li>
    </ul>
</div>

CustomerPortal/Views/Shared/_Grid.cshtml
@using GridMvc.Columns
@model GridMvc.IGrid
@if (Model == null) { return; }
@if (Model.RenderOptions.RenderRowsOnly)
{
    @RenderGridBody();
}
else
{
    <div class="grid-mvc" data-lang="@Model.Language" data-gridname="@Model.RenderOptions.GridName" data-selectable="@Model.RenderOptions.Selectable.ToString().ToLower()" data-multiplefilters ="@Model.RenderOptions.AllowMultipleFilters.ToString().ToLower()">
        <div class="grid-wrap">
            <table class="table table-striped grid-table">
                @* Draw grid header *@
                <thead>
                    @RenderGridHeader()
                </thead>
                <tbody>
                    @RenderGridBody()
                </tbody>
            </table>
            @RenderGridPager()
        </div>
    </div>
}
@helper RenderGridBody()
{
    if (!Model.ItemsToDisplay.Any())
    {
    <tr class="grid-empty-text">
        <td colspan="@Model.Columns.Count()">
            @Model.EmptyGridText
        </td>
    </tr>
    }
    else
    {
        foreach (object item in Model.ItemsToDisplay)
        {
    <tr class="grid-row @Model.GetRowCssClasses(item)">
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.CellRenderer.Render(column, column.GetCell(item))
        }
    </tr>
        }
    }
}
@helper RenderGridHeader()
{
    <tr>
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.HeaderRenderer.Render(column)
        }
    </tr>
}
@helper RenderGridPager()
{
    if (Model.EnablePaging && Model.Pager != null)
    {
    <div class="grid-footer">
        @Html.Partial(Model.Pager.TemplateName, Model.Pager)
    </div>
    }
}

CustomerPortal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    <link href="~/siteicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE10" />
    <link href="../../Content/metro.css" rel="stylesheet">
    <link href="../../Content/site.css" rel="stylesheet">
    <link href="../../Content/metro-icons.min.css" rel="stylesheet">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <script src="../../Scripts/metro.js"></script>

    <!-- Google Analytics Start -->
    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date(); a = s.createElement(o),
            m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
        })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-4123848-3', 'auto');
        ga('send', 'pageview');

        navigator.sayswho = (function () {
            var ua = navigator.userAgent, tem,
                M = ua.match(/(opera|chrome|safari|firefox|msie|trident(?=\/))\/?\s*(\d+)/i) || [];
            if (/trident/i.test(M[1])) {
                tem = /\brv[ :]+(\d+)/g.exec(ua) || [];
                return 'IE ' + (tem[1] || '');
            }
            if (M[1] === 'Chrome') {
                tem = ua.match(/\b(OPR|Edge)\/(\d+)/);
                if (tem != null) return tem.slice(1).join(' ').replace('OPR', 'Opera');
            }
            M = M[2] ? [M[1], M[2]] : [navigator.appName, navigator.appVersion, '-?'];
            if ((tem = ua.match(/version\/(\d+)/i)) != null) M.splice(1, 1, tem[1]);
            return M.join(' ');
        })();

        $(function () {
            $(".addToCart").ajaxForm({
                target: '#shopTop',
                beforeSubmit: function () { },
                success: function (result) {
                    $("#shopTop").html(result.view).show();

                    if (result.message.Type == 'Success') {
                        $.Notify({
                            icon: '<span class="fa fa-cart-plus"></span>',
                            caption: result.message.Title,
                            content: result.message.Content,
                            type: result.message.Type.toLowerCase()
                        });
                    }
                    else {
                        $.Notify({
                            icon: '<span class="fa fa-exclamation-triangle fg-crimson"></span>',
                            caption: result.message.Title,
                            content: result.message.Content,
                            style: { background: '#FFF', color: '#000' }
                        });
                    }
                }
            });
        });
    </script>
    <!-- Google Analytics End -->
</head>
<body>

    @*    <div style="width: 100%; height: 100px; color: White; font-size: 40px; margin-top: 10px" class="bg-violet">
        <div style="width: 70%; margin: auto;">
        </div>
    </div>*@
    <div class="container">
        @{ if (User.Identity.IsAuthenticated)
           {
            <header class="margin20 no-margin-left no-margin-right">
            <div class="clear-float">
                <div class="place-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                        <br />
                    </section>
                    
                    @if (Roles.IsUserInRole("PlaceOrders"))
                    {
                        Html.RenderAction("ShoppingCartIcon", "ShoppingCart");
                    }
                </div>
                <a class="place-left" href="/Home" title="">
                    <img alt="logo" src="../../Images/logo.jpg" width="200" />
                </a>
            </div>

            <div class="main-menu-wrapper">
                @if (!string.IsNullOrEmpty(((CustomerPortalModels.User)Session["user"]).CustomerNumber))
                {
                    <ul class="horizontal-menu" style="margin-left: -20px">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        @if (Roles.IsUserInRole("ViewOrders"))
                        {
                            if (Roles.IsUserInRole("Administrator"))
                            {
                                <li>
                                    <a href="#" class="dropdown-toggle">Orders</a>
                                    <ul class="d-menu" data-role="dropdown">
                                        <li>@Html.ActionLink("Orders", "Index", "Order")</li>
                                        <li>@Html.ActionLink("Test", "ProcessCheckout", "ShoppingCart")</li>
                                    </ul>
                                </li>
                            }
                            else
                            {
                                <li>@Html.ActionLink("Orders", "Index", "Order")</li>
                            }
                        }
                        @if (Roles.IsUserInRole("PayInvoices"))
                        {
                            <li>@Html.ActionLink("Invoices", "Index", "Invoice")</li>
                        }
                        <li>
                            <a href="#" class="dropdown-toggle">Products</a>
                            <ul class="d-menu" data-role="dropdown">
                                <li>@Html.ActionLink("All Products", "Index", "Product")</li>
                                <li>@Html.ActionLink("Favorites", "FavoriteList", "Product")</li>
                                @if (Roles.IsUserInRole("PlaceOrders"))
                                {
                                    <li>@Html.ActionLink("Import Shopping List", "ImportShoppingList", "ShoppingCart")</li>
                                }
                            </ul>
                        </li>
                        @if (Roles.IsUserInRole("UseTools"))
                        {
                            <li>
                                <a href="#" class="dropdown-toggle">Resources</a>
                                <ul class="d-menu" data-role="dropdown">
                                    <li>@Html.ActionLink("Downloads", "Downloads", "Resource")</li>
                                    <li>@Html.ActionLink("Cross Reference", "CrossReferenceTool", "Resource")</li>
                                </ul>
                            </li>
                        }
                        @if (Roles.IsUserInRole("CreateUsers"))
                        {
                            <li>
                                <a href="#" class="dropdown-toggle">Users</a>
                                <ul class="d-menu" data-role="dropdown" data-no-close="true">
                                    <li>@Html.ActionLink("Search Users", "Index", "User")</li>
                                    <li>@Html.ActionLink("Account Requests", "AccountRequests", "Account")</li>
                                    <li><a href="#" class="dropdown-toggle">Create User</a>
                                        <ul class="d-menu" data-role="dropdown" data-no-close="true">
                                            @if (Roles.IsUserInRole("Administrator"))
                                            {
                                                <li>@Html.ActionLink("Administrator", "RegisterAdministrator", "Account")</li>
                                                <li>@Html.ActionLink("Power User", "RegisterPowerUser", "Account")</li>
                                            }
                                            @if (Roles.IsUserInRole("PowerUser"))
                                            {
                                                <li>@Html.ActionLink("Internal", "RegisterInternalUser", "Account")</li>
                                            }
                                            <li>@Html.ActionLink("Customer", "RegisterCustomer", "Account")</li>
                                            <li>@Html.ActionLink("Rep Group", "RegisterRepGroup", "Account")</li>
                                        </ul>
                                    </li>
                                </ul>
                            </li>
                        }
                    </ul>
                }
                else
                {
                    <ul class="horizontal-menu" style="margin-left: -20px">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>
                            <a href="#" class="dropdown-toggle">Resources</a>
                            <ul class="d-menu" data-role="dropdown">
                                <li>@Html.ActionLink("Downloads", "Downloads", "Resource")</li>
                            </ul>
                        </li>
                        @if (Roles.IsUserInRole("CreateUsers"))
                        {
                            <li>
                                <a href="#" class="dropdown-toggle">Users</a>
                                <ul class="d-menu" data-role="dropdown" data-no-close="true">
                                    <li>@Html.ActionLink("Search Users", "Index", "User")</li>
                                    <li>@Html.ActionLink("Account Requests", "AccountRequests", "Account")</li>
                                    <li><a href="#" class="dropdown-toggle">Create User</a>
                                        <ul class="d-menu" data-role="dropdown" data-no-close="true">
                                            @if (Roles.IsUserInRole("Administrator"))
                                            {
                                                <li>@Html.ActionLink("Administrator", "RegisterAdministrator", "Account")</li>
                                                <li>@Html.ActionLink("Power User", "RegisterPowerUser", "Account")</li>
                                            }
                                            @if (Roles.IsUserInRole("PowerUser"))
                                            {
                                                <li>@Html.ActionLink("Internal", "RegisterInternalUser", "Account")</li>
                                            }
                                            <li>@Html.ActionLink("Customer", "RegisterCustomer", "Account")</li>
                                            <li>@Html.ActionLink("Rep Group", "RegisterRepGroup", "Account")</li>
                                        </ul>
                                    </li>
                                </ul>
                            </li>
                        }
                    </ul>
                }
            </div>
            <a href="https://us.pipglobal.com/email/pip/2019/190501-West-Chester-Customer-Portal.html"><img alt="WC Portal Shutdown Alert" src="../../Images/WC-Portal-Alert.png" style="width:1110px; height:150px;" /></a>
        </header>
            @RenderBody()
            <br class="clear" />
            <footer>
                @Html.Partial("_FooterPartial")
            </footer>
           }
           else
           {
            <link href="../../Content/NoAuth.css" rel="stylesheet">
            <div class="content">
                <div class="login-logo">
                    <a style="margin: auto" href="#" title=""></a>
                </div>
                @RenderBody()
            </div>
           }
        }
    </div>
</body>
@RenderSection("Scripts", required: false)