CustomerPortal/Models/CheckoutStep1.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Globalization;
using System.Web.Mvc;
using System.Web.Security;

namespace CustomerPortal.Models
{
    public class CheckoutStep1
    {
        [Required]
        [Display(Name = "Company Name")]
        public string CompanyName { get; set; }

        [Display(Name = "Attention")]
        public string Attention { get; set; }

        [Required]
        [Display(Name = "PO Number")]
        public string PONumber { get; set; }

        [Display(Name = "Customer PO Number")]
        public string CustomerPONumber { get; set; }

        [Required]
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Required]
        [Display(Name = "Phone Number")]
        public string PhoneNumber { get; set; }

        [Display(Name = "Payment Terms")]
        public string PaymentTerms { get; set; }

        [Display(Name = "Carrier")]
        public string Carrier { get; set; }

        [Display(Name = "Account Number")]
        public string AccountNumber { get; set; }

        [Display(Name = "Shipping Instructions")]
        public string ShippingInstructions { get; set; }
    }
}

CustomerPortal/Models/CheckoutStep2.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Globalization;
using System.Web.Mvc;
using System.Web.Security;

namespace CustomerPortal.Models
{
    public class CheckoutStep2
    {
        [Required]
        [Display(Name = "Ship To")]
        public string ShipToID { get; set; }

        [Required]
        public string State { get; set; }

        [Required]
        public string City { get; set; }

        [Required]
        public string Street { get; set; }

        [Required]
        public string Zip { get; set; }

        [Required]
        public string Name { get; set; }
		
		[Required]
        [Display(Name = "Request as Permanent Shipping Address")]
        public bool RequestPermanent { get; set; }
       
    }
}

CustomerPortal/Models/ShoppingCart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using CustomerPortalModels;

namespace CustomerPortal.Models
{
    public class ShoppingCart
    {
        public virtual int ID { get; set; }
        public virtual string UserName { get; set; }
        public virtual IList<CartLineItem> LineItems { get; set; }

        public virtual int Count
        {
            get
            {
                return (from x in LineItems where !x.Sample select x.Quantity).Sum();
            }
        }

        public virtual int SampleCount
        {
            get
            {
                return (from x in LineItems where x.Sample select x).Count();
            }
        }

        public virtual double Total
        {
            get
            {
                return (from x in LineItems select (x.TotalPrice)).Sum();
            }
        }

        public ShoppingCart()
        {
            LineItems = new List<CartLineItem>();
        }

        public override bool Equals(object obj)
        {
            var cart = (ShoppingCart)obj;

            return UserName == cart.UserName
                && ID == cart.ID
                && Count == cart.Count
                && SampleCount == cart.SampleCount
                && LineItems.Count == cart.LineItems.Count;

            return base.Equals(obj);
        }
    }
}

CustomerPortal/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CustomerPortal.Models;
using System.IO;
using OfficeOpenXml;
using System.Text.RegularExpressions;
using CustomerPortalModels;
using SAP.Middleware.Connector;
using System.Web.Security;
using NCommon.Specifications;
using System.Data.SqlClient;
using System.Configuration;

namespace CustomerPortal.Controllers
{
    [Authorize]
    public class ShoppingCartController : _ApplicationController
    {
        private readonly IShoppingCartRepository _cartRepo;
        private readonly IProductRepository _productRepo;
        private readonly IOrderRepository _orderRepo;
        private readonly IOrderLineRepository _orderLineRepo;
        private readonly ICustomerRepository _customerRepo;
        private readonly IUserActivityRepository _userActivityRepo;
        private readonly ICheckoutDataRepository _checkoutDataRepo;

        public ShoppingCartController(IShoppingCartRepository cartRepo, IProductRepository productRepo, IOrderRepository orderRepo, IOrderLineRepository orderLineRepo, ICustomerRepository customerRepo, IUserActivityRepository userActivityRepo, ICheckoutDataRepository checkoutDataRepo)
        {
            _cartRepo = cartRepo;
            _productRepo = productRepo;
            _orderRepo = orderRepo;
            _orderLineRepo = orderLineRepo;
            _customerRepo = customerRepo;
            _userActivityRepo = userActivityRepo;
            _checkoutDataRepo = checkoutDataRepo;
        }

        public ActionResult Index()
        {
            return View(GetCart());
        }

        [HttpPost]
        public ActionResult CheckoutList()
        {
            var checkouts = _checkoutDataRepo.GetAll().Where(x => !x.Success);
            return View(checkouts);
        }

        private ShoppingCart GetCart()
        {
            if (!string.IsNullOrEmpty(GetUser().CustomerNumber))
            {
                var cart = _cartRepo.Get(GetUser().UserName);

                if (Session["shoppingCart"] != null && ((ShoppingCart)Session["shoppingCart"]).Equals(cart))
                    return (ShoppingCart)Session["shoppingCart"];

                for (int i = 0; i < cart.LineItems.Count; i++)
                {
                    var line = cart.LineItems[i];
                    line.Product = _productRepo.Get(line.SKU, GetUser().CustomerNumber);

                    // if the product is no longer valid, remove the line item.
                    if (line.Product == null)
                    {
                        _cartRepo.RemoveItemFromCart(line.SKU, GetUser().UserName);

                        // Get the cart again to reflect removed line items
                        cart = _cartRepo.Get(GetUser().UserName);
                    }
                }

                Session["shoppingCart"] = cart;
                return cart;
            }
            else
                return new ShoppingCart();
        }

        public ActionResult ShoppingCartIcon()
        {
            ShoppingCart cart = GetCart();

            return PartialView(cart);
        }

        [HttpPost]
        public ActionResult AddToCart(AddToCartModel model)
        {
            Message message;

            model.SKU = model.SKU.ToUpper();
            var product = _productRepo.Get(model.SKU, GetUser().CustomerNumber);

            if (product != null)
            {
                // if quantity less than 1, make 1. Capitalize sku
                model.Quantity = model.Quantity < 1 ? 1 : model.Quantity;
                model.SKU = model.SKU;

                // store in persistent cart
                _cartRepo.AddItemToCart(model.SKU, model.Quantity, GetUser().UserName, false);

                message = new Message()
                {
                    Type = "Success",
                    Title = "Item Added",
                    Content = string.Format("{0} of {1} added to your cart.", model.Quantity, model.SKU)
                };
            }
            else
            {
                message = new Message()
                {
                    Type = "Failure",
                    Title = "Item Not Added to Cart",
                    Content = string.Format("Item '{0}' does not exist.", model.SKU)
                };
            }

            return Json(new { message = message, view = RenderViewToString("ShoppingCartIcon", GetCart()) });
        }

        [HttpPost]
        public ActionResult AddSampleToCart(string sku)
        {
            var product = _productRepo.Get(sku, GetUser().CustomerNumber);

            // store in persistent cart
            _cartRepo.AddItemToCart(sku, 1, GetUser().UserName, true);

            var message = new Message()
            {
                Type = "success",
                Title = "Item Added",
                Content = string.Format("A sample of {0} added to your cart.", sku)
            };

            return Json(new { message = message, view = RenderViewToString("ShoppingCartIcon", GetCart()) });
        }

        [HttpPost]
        public ActionResult UpdateLineItem(AddToCartModel model)
        {
            _cartRepo.UpdateLineItem(model.SKU, model.Quantity, GetUser().UserName);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult RemoveLineItem(CustomerPortalModels.Product product)
        {
            _cartRepo.RemoveItemFromCart(product.SKU, GetUser().UserName);
            return RedirectToAction("Index");
        }

        public ActionResult ClearCart()
        {
            _cartRepo.ClearCart(GetUser().UserName);
            return View("Index", GetCart());
        }

        public ActionResult Checkout()
        {
            return View();
        }

        [HttpGet]
        public ActionResult CheckoutStep1()
        {
            CheckoutStep1 model = new CheckoutStep1();
            model.Email = User.Identity.Name;
            model.CompanyName = _customerRepo.Get(GetUser().CustomerNumber).Name;
            return PartialView(model);
        }

        [HttpPost]
        public ActionResult CheckoutStep1(CheckoutStep1 model)
        {
           /* string q = "SELECT * FROM prd.VAKPA WHERE(MANDT = '100') AND(KUNDE = @custnum) AND(PARVW = 'AG') AND(BSTNK = @ponum)";
            SqlConnection conn = new SqlConnection(ConfigurationManager.ConnectionStrings["SAPConnection"].ConnectionString);
            conn.Open();
            SqlCommand cmd = new SqlCommand(q, conn);
            cmd.Parameters.Add(new SqlParameter("@ponum", System.Data.SqlDbType.VarChar));
            cmd.Parameters["@ponum"].Value = model.PONumber;
            cmd.Parameters.Add(new SqlParameter("@custnum", System.Data.SqlDbType.VarChar));
            cmd.Parameters["@custnum"].Value = GetUser().CustomerNumber;
            SqlDataReader reader = cmd.ExecuteReader();

            if (reader.HasRows)
            {
                ModelState.AddModelError("", "PO Number Must be unique.");
                return PartialView("CheckoutStep1", model);
            }
            */
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "The highlighted fields are required..");
                return PartialView("CheckoutStep1", model);
            }
            else
            {
                var checkout = GetCheckout();
                checkout.Attention = model.Attention;
                checkout.CompanyName = model.CompanyName;
                checkout.PONumber = model.PONumber;
                checkout.CustomerPONumber = model.CustomerPONumber;
                checkout.Email = model.Email;
                checkout.PhoneNumber = model.PhoneNumber;
                checkout.PaymentTerms = model.PaymentTerms;
                checkout.AccountNumber = model.AccountNumber;
                checkout.Carrier = model.Carrier;
                checkout.ShippingInstructions = model.ShippingInstructions;
                return Json(new { success = true });
            }
        }

        [HttpPost]
        public ActionResult CheckoutStep2(CheckoutStep2 model)
        {
            if (!ModelState.IsValid)
            {
                return PartialView("CheckoutStep2", model);
            }
            else
            {
                var checkout = GetCheckout();
                checkout.ShipToID = model.ShipToID;
                checkout.Street = model.Street;
                checkout.City = model.City;
                checkout.State = model.State;
                checkout.Zip = model.Zip;
                checkout.Name = model.Name;
                return Json(new { success = true, view = RenderViewToString("ConfirmCheckout", GetCheckout()) });
            }
        }

        [HttpPost]
        public ActionResult SelectShippingAddress(CheckoutModel model, string BtnPrevious, string BtnNext)
        {
            var checkout = GetCheckout();
            if (BtnPrevious != null)
            {
                return View("Checkout", checkout);
            }
            if (BtnNext != null)
            {
                if (ModelState.IsValid)
                {
                    checkout = model;
                    return View("SelectShippingAddress", model);
                }
            }

            return View();
        }

        [HttpPost]
        public ActionResult ConfirmCheckout(CheckoutModel model)
        {
            CheckoutResponse response = new CheckoutResponse();
            var notice_email = model.NotificationEmail;
            try
            {
                model = GetCheckout();

                model.Cart = GetCart();


CustomerPortal/Views/ShoppingCart/CheckoutStep1.cshtml
@model CustomerPortal.Models.CheckoutStep1

<div>
    @using (Html.BeginForm("CheckoutStep1", "ShoppingCart", FormMethod.Post, new { id = "step1Form" }))
    {
        @Html.AntiForgeryToken()
        <h1 class="page-title text-light">
            Checkout</h1>
        <hr class="thin" />
        <br />
        if (ViewData.ModelState.Any())
        {
        @Html.ValidationSummary(true)
        <br />
        }
        <div class="input-control text" data-role="input">
            @Html.LabelFor(m => m.CompanyName)
            @Html.TextBoxFor(m => m.CompanyName)
        </div>
        <br />
        <br />
        <div class="input-control text" data-role="input">
            @Html.LabelFor(m => m.Attention)
            @Html.TextBoxFor(m => m.Attention)
        </div>
        <br />
        <br />
        <div class="input-control text" data-role="input">
            @Html.LabelFor(m => m.PONumber)
            @Html.TextBoxFor(m => m.PONumber)
        </div>
        <br />
        <br />
        <div class="input-control text" data-role="input">
            @Html.LabelFor(m => m.CustomerPONumber)
            @Html.TextBoxFor(m => m.CustomerPONumber)
        </div>
        <br />
        <br />
        <div class="input-control text" data-role="input">
            @Html.LabelFor(m => m.Email)
            @Html.TextBoxFor(m => m.Email)
        </div>
        <br />
        <br />
        <div class="input-control text" data-role="input">
            @Html.LabelFor(m => m.PhoneNumber)
            @Html.TextBoxFor(m => m.PhoneNumber)
        </div>
        <br />
        <br />
        <div class="input-control select">
            <select name="PaymentTerms" id="PaymentTerms">
                <option selected="selected">ADD</option>
                <option>COL</option>
                <option>3RD</option>
            </select>
        </div>
        <fieldset id="AccountNumberDiv" style="margin-left: -5px; padding: 0 8px 0 3px; margin-right:-10px">
            <br />
            <br />
            <div class="input-control text" data-role="input">
                @Html.LabelFor(m => m.Carrier)
                @Html.TextBoxFor(m => m.Carrier)
            </div>
            <br />
            <br />
            <div class="input-control text" data-role="input">
                @Html.LabelFor(m => m.AccountNumber)
                @Html.TextBoxFor(m => m.AccountNumber)
            </div>
            <br />
        </fieldset>
        <br />
        <br />
        <div class="input-control text" data-role="input">
            @Html.LabelFor(m => m.ShippingInstructions)
            @Html.TextBoxFor(m => m.ShippingInstructions)
        </div>
    }

</div>

CustomerPortal/Views/ShoppingCart/CheckoutStep2.cshtml
@model CustomerPortal.Models.CheckoutStep2
@{
    ViewBag.Title = "Checkout";
}

<h1 class="page-title text-light">
    Select a Shipping Address</h1>
<hr class="thin" />
<div style="width: 50%; display: none" id="checkoutForm">

    <h4 style="float:left">Please enter a drop shipment address</h4>
    <div class="advancedSearchLink">
        <a href="#" onclick="toggleOneTime()">
            Back to Address Book
        </a>
    </div>
    <br class="clear" />
    @using (Html.BeginForm("CheckoutStep2", "ShoppingCart", FormMethod.Post, new { id = "step2Form" }))
    {
        @Html.AntiForgeryToken()
        <br />
        if (ViewData.ModelState.Any())
        {
            @Html.ValidationSummary(false)
            <br />
        }
        @Html.HiddenFor(m => m.ShipToID)
        <div class="input-control text full-size" data-role="input">
            @Html.LabelFor(m => m.Street)
            @Html.TextBoxFor(m => m.Street)
        </div>
        <br />
        <br />
        <div class="input-control text full-size" data-role="input">
            @Html.LabelFor(m => m.City)
            @Html.TextBoxFor(m => m.City)
        </div>
        <br />
        @Html.LabelFor(m => m.State)
        <br />
        <div class="input-control select half-size" data-role="input">
            <select id="State" name="State">
                <option value="AL">Alabama</option>
                <option value="AK">Alaska</option>
                <option value="AZ">Arizona</option>
                <option value="AR">Arkansas</option>
                <option value="CA">California</option>
                <option value="CO">Colorado</option>
                <option value="CT">Connecticut</option>
                <option value="DE">Delaware</option>
                <option value="DC">District Of Columbia</option>
                <option value="FL">Florida</option>
                <option value="GA">Georgia</option>
                <option value="HI">Hawaii</option>
                <option value="ID">Idaho</option>
                <option value="IL">Illinois</option>
                <option value="IN">Indiana</option>
                <option value="IA">Iowa</option>
                <option value="KS">Kansas</option>
                <option value="KY">Kentucky</option>
                <option value="LA">Louisiana</option>
                <option value="ME">Maine</option>
                <option value="MD">Maryland</option>
                <option value="MA">Massachusetts</option>
                <option value="MI">Michigan</option>
                <option value="MN">Minnesota</option>
                <option value="MS">Mississippi</option>
                <option value="MO">Missouri</option>
                <option value="MT">Montana</option>
                <option value="NE">Nebraska</option>
                <option value="NV">Nevada</option>
                <option value="NH">New Hampshire</option>
                <option value="NJ">New Jersey</option>
                <option value="NM">New Mexico</option>
                <option value="NY">New York</option>
                <option value="NC">North Carolina</option>
                <option value="ND">North Dakota</option>
                <option value="OH">Ohio</option>
                <option value="OK">Oklahoma</option>
                <option value="OR">Oregon</option>
                <option value="PA">Pennsylvania</option>
                <option value="RI">Rhode Island</option>
                <option value="SC">South Carolina</option>
                <option value="SD">South Dakota</option>
                <option value="TN">Tennessee</option>
                <option value="TX">Texas</option>
                <option value="UT">Utah</option>
                <option value="VT">Vermont</option>
                <option value="VA">Virginia</option>
                <option value="WA">Washington</option>
                <option value="WV">West Virginia</option>
                <option value="WI">Wisconsin</option>
                <option value="WY">Wyoming</option>
            </select>
        </div>
        <br />
        <br />
        <div class="input-control text half-size" data-role="input">
            @Html.LabelFor(m => m.Zip)
            @Html.TextBoxFor(m => m.Zip)
        </div>
        <br />
        <br />
        <div class="input-control text full-size" data-role="input">
            @Html.LabelFor(m => m.Name)
            @Html.TextBoxFor(m => m.Name)
        </div>
        <div data-role="input">
            @Html.CheckBoxFor(m => m.RequestPermanent)
            @Html.LabelFor(m => m.RequestPermanent, new { @class = "checkbox" })
        </div>
       
    }
</div>

CustomerPortal/Views/ShoppingCart/ConfirmCheckout.cshtml
@model CustomerPortal.Models.CheckoutModel

@{
    ViewBag.Title = "Confirm Checkout";
}

@using (Html.BeginForm("ConfirmCheckout", "ShoppingCart", FormMethod.Post, new { id = "step3Form" }))
{
    if (Model != null)
    {
    @Html.AntiForgeryToken()
            <h1 class="page-title text-light">Confirm Checkout</h1>
            <hr class="thin"/>
            <br />
        if (ViewData.ModelState.Any())
        {
                  @Html.ValidationSummary(true)
            <br />
        }
            <div class="input-control text" data-role="input">
                @Html.LabelFor(m => m.CompanyName)
                @Html.HiddenFor(m => m.CompanyName)
                @Model.CompanyName
            </div>
            <br />
            <br />
            <div class="input-control text" data-role="input">
                @Html.LabelFor(m => m.Attention)
                @Html.HiddenFor(m => m.Attention)
                @Model.Attention
            </div>
            <br />
            <br />
            <div class="input-control text" data-role="input">
                @Html.LabelFor(m => m.ShipToID)
                @Html.HiddenFor(m => m.ShipToID)
                @Model.ShipToID
                @Html.HiddenFor(m => m.Street)
                @Html.HiddenFor(m => m.City)
                @Html.HiddenFor(m => m.State)
                @Html.HiddenFor(m => m.Zip)
                @Html.HiddenFor(m => m.Name)
            </div>
            <br />
            <br />
            <div class="input-control text" data-role="input">
                @Html.LabelFor(m => m.PONumber) 
                @Html.HiddenFor(m => m.PONumber)
                @Model.PONumber
            </div>
            <br />
            <br />
            <div class="input-control text" data-role="input">
                @Html.LabelFor(m => m.CustomerPONumber)
                @Html.HiddenFor(m => m.CustomerPONumber)
                @Model.CustomerPONumber
            </div>
            <br />
            <br />
            <div class="input-control text" data-role="input">
                @Html.LabelFor(m => m.Email)
                @Html.HiddenFor(m => m.Email)
                @Model.Email
            </div>
            <br />
            <br />
            <div class="input-control text" data-role="input">
                @Html.LabelFor(m => m.PhoneNumber)
                @Html.HiddenFor(m => m.PhoneNumber)
                @Model.PhoneNumber
            </div>
            <br />
            <br />
            <div class="input-control text" data-role="input">
                @Html.LabelFor(m => m.PaymentTerms)
                @Html.HiddenFor(m => m.PaymentTerms)
                @Html.DisplayTextFor(m => m.PaymentTerms)
            </div>
            <br />
            <br />
            <div class="input-control text" data-role="input">
                @Html.LabelFor(m => m.ShippingInstructions)
                @Html.HiddenFor(m => m.ShippingInstructions)
                @Model.ShippingInstructions
            </div>
            <br />
            <br />
              <div class="input" data-role="input">
                @Html.CheckBoxFor(m => m.sendNotification, new { @onclick = "ChangeNotificatnEmailVisible(this)" } )
                @Html.LabelFor(m => m.sendNotification, new { @class = "checkbox" })
                <div class="NotificationShow">
                    @Html.LabelFor(m => m.NotificationEmail) <br />
                    @Html.TextBoxFor(m => m.NotificationEmail)
                </div>
            </div> 
    }
}

<div data-role="dialog" id="placeOrderMessage" data-windows-style="true" class="bg-emerald fg-white">
    <div style="width: 33%; float:left">
        <span style="display:flex;justify-content:center;align-items:center;width:100%;font-size:100px;" class="fg-white"></span>
    </div>
    <div class="fullScreenInner">
        <div>
            <h1>Your order is being processed.</h1>
            <p>
                Please be patient, this may take a moment.
            </p>
        </div>
    </div>
</div>

<div class="modalDialog"></div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CustomerPortal/Views/ShoppingCart/Index.cshtml
@model CustomerPortal.Models.ShoppingCart
@using MvcContrib.UI.Grid
@section Scripts
{
    <link href="@Url.Content("~/Scripts/__jquery.tablesorter/themes/custom/style.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Scripts/__jquery.tablesorter/addons/pager/jquery.tablesorter.pager.css")" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="../../Scripts/__jquery.tablesorter/jquery.tablesorter.js?1"></script>
    <script type="text/javascript" src="../../Scripts/__jquery.tablesorter/addons/pager/jquery.tablesorter.pager.js?1"></script>
    <script type="text/javascript">
        noStock = [];
        processing = [];
        processed = 0;
        checkingOut = false;

        @foreach (var line in Model.LineItems)
        {
            @:processing.push('@line.Product.SKU');
        }

        $(document).ready(function () {
            $("#cart")
            .tablesorter({ widthFixed: true, headers: { 1: { sorter: false}, 3: { sorter: false}, 5: { sorter: false}} })
        });

        function showDialog(id) {
            checkingOut = true;
            if (processed < @Model.LineItems.Count)
            {
                $('#processingMessage').html(processing.join('<br />'));
                var dialog = $('#stockDialog').data('dialog');
                dialog.open();
            }
            else {
                showOutOfStock();
            }
        }

        function showOutOfStock() {
            hideDialog('#stockDialog');
            if (noStock.length > 0) {
                $('#noStockMessage').html(noStock.join(', '));
                var dialog = $('#dialog').data('dialog');
                dialog.open();
            }
            else {
                proceedOrder();
            }
        }

        function hideDialog(id) {
            var dialog = $(id).data('dialog');
            dialog.close();
        }

        function proceedOrder() {
            document.forms["proceedCheckout"].submit();
        }

        function sleep(milliseconds) {
            var start = new Date().getTime();
            for (var i = 0; i < 1e7; i++) {
                if ((new Date().getTime() - start) > milliseconds){
                    break;
                }
            }
        }
    </script>
}

<div id="dialog" class="padding20 dialog" data-role="dialog" data-width="500" 
    data-background="bg-red" data-color="fg-white" >
    <div>
        <h3>Some items in your cart are currently unavailable</h3>
        <p>The following items:</p>
        <p id="noStockMessage"></p>
        <p>will be placed onto backorder.</p>
        <button class="button" onclick="proceedOrder()" style="float:right">Proceed</button>
        <button class="button" onclick="hideDialog('#dialog')" style="float:left">Back to Cart</button>
    </div>
</div>

<div id="stockDialog" class="padding20 dialog" data-role="dialog" data-width="500" 
    data-background="bg-white" data-color="fg-black" style="border:1px solid #000000">
    <div>
        <h3>We are still calculating stock availability for these items:</h3>
        <p id="processingMessage"></p>
        <button class="button" onclick="proceedOrder()" style="float:right">Skip</button>
    </div>
</div>
<h2>
    Your Cart</h2>
@{
    var colors = new List<string>() { "yellow", "light-blue", "red", "green" };

    if (Model != null && Model.LineItems.Count > 0)
    {
        Html.Grid(Model.LineItems)
            .Attributes(@id => "cart", @class => "tablesorter", style => "width:100%")
            .RowAttributes(row => new MvcContrib.Hash(@class => colors[Model.LineItems.ToList().IndexOf(row.Item) % 4]))
            .Columns(
                col =>
                {
                    col.For(x => Html.Partial("ProductPhotoLink", x.Product)).Named("SKU");
                    col.For(x => Html.Partial("_InStockPartial", x)).Named("In Stock");
                    col.For(x => x.Sample ? "Sample" : Html.Partial("_PriceDisplay", x.Product).ToString()).Encode(false).Named("Price");
                    col.For(x => x.Sample ? Html.Label("") : Html.Partial("UpdateLineItemPartial", new CustomerPortal.Models.AddToCartModel()
                    {
                        Quantity = x.Quantity,
                        SKU = x.SKU
                    }));
                    col.For(x => x.Sample ? "Sample" : string.Format("{0:c}", x.TotalPrice)).Attributes(@class => "bold-column").Named("Total Price");
                    col.For(x => Html.Partial("RemoveLineItemPartial", x.Product)).Attributes(@class => "right-column");
                }).Render();
        
        <div style="width: 100%; border-bottom: 8px solid #444">
        </div>
        <br />
        <div style="float:right">
            <b>Cart Total: @string.Format("{0:c}", Model.Total)</b>
            <form id="proceedCheckout" action="ShoppingCart/Checkout">
                <button id="checkoutButton" type="button" class="button" onclick="showDialog('#dialog')">Checkout</button>
            </form>
        </div>
        @Html.ActionLink("Clear Cart", "ClearCart")
        <br />
        <br />
        <br />
    }
    else
    {
        <br class="clear" />
        <h4 class="emptyMessage">There are no items in your shopping cart.</h4>
    }
    
    if (Roles.IsUserInRole("Administrator"))
    {
        using (Html.BeginForm("CheckoutList", "ShoppingCart"))
        {
            <div class="input-control input-control text" style="width: 10px">
                <button class="button">
                    View Failed Carts
                </button>
            </div>
        }
    }
}